server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name lixs.fun www.lixs.fun _;

    root /var/www/lixs.fun;

    location /.well-known/acme-challenge/ {
        root /var/www/lixs.fun;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
